name: Build and Push Docker Image

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # 1. Get the code from repo
            - name: Checkout repository
              uses: actions/checkout@v4
            
            # 2. Set up Docker Buildx builder
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # 3. Login to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # 4. Build and push Docker image
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest
            